### ISSUE TITLE
certificate verify failed: certificate has expired 

### ISSUE THREAD

**Issue by shenronUber** [ESA-VirES/Aeolus-notebooks#32]
hello,

I'm trying to use the Aeolus viresclient library on my local machine, because of the memory restrictions on the web client.
I've set up a jupyter notebook through anaconda and the viresclient library was successfully downloaded.

However, when trying to request a data retrieval, I am receiving this error :
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>

I have created multiple new tokens and tried with and without "Bearer", but I am still met with the same issue.
I followed the online guides but found no mentions of this specific error.

On my online VRE, everything works fine. I'm just trying to port my notebook to my local machine in order to get some extra memory.

I've also attached the error log to this thread.

Thanks again !

[Error_log.txt](https://github.com/ESA-VirES/Aeolus-notebooks/files/8871268/Error_log.txt)

**Comment by pacesm** [comment]
This error is most likely caused by an old version of the OpenSSL library on your computer (Anaconda environment). Please make sure you are using [OpenSSL version 1.1.0 or later](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)

This issue is not related to the validity of the access token.
